<h1>ISB2017 Applied Data Science<h1>

---


***Lab Exercise Week 1: Introduction to Python***

<h3> Berinteraksi dengan NumPy </h3>

1.1 Import numpy dan lihat versinya

1.2 Bagaimana cara kita membuat numpy Array 1D?

1.3 Bagaimana cara kita membuat numpy Array 2D?

1.4 Bagaimana membuat array 1D yang isinya 0

1.5 Buatlah numpy array yang isinya acak

In [2]:
# Jawaban 1.1
import numpy as np
print(np.version.version)

1.19.1


In [7]:
# Jawaban 1.2
array_1d = np.array([1, 2, 3, 4])
array_1d

array([1, 2, 3, 4])

In [8]:
# Jawaban 1.3
array_2d = np.array([[1, 2], [3, 4]])
array_2d

array([[1, 2],
       [3, 4]])

In [9]:
# Jawaban 1.4
array_0 = np.zeros(4)
array_0

array([0., 0., 0., 0.])

In [10]:
# Jawaban 1.5
arr_rand = np.random.randint(10, 20, size=(5))
arr_rand

array([14, 16, 10, 17, 15])

<h3> Berinteraksi dengan Numpy Array </h3>

In [11]:
import numpy as np
sebuah_list = [[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]]
arr = np.array(sebuah_list, dtype='float')
arr

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

2.1 Temukan Ukuran, Dimensi, Bentuk, dan tipe data **arr** diatas

2.2 Bagaimana mendapatkan data 2., 3., 6., 7., 10., 11.

2.3 Ubahlan tipe data **arr** di atas menjadi integer

2.4 Ubahla dimensi **arr** di atas menjadi 2x6

In [13]:
# Jawaban 2.1
print("Dimensi: ", arr.ndim)
print("Bentuk: ", arr.shape)
print("Ukuran: ", arr.size)
print("Tipe Data: ", arr.dtype)

Dimensi:  2
Bentuk:  (3, 4)
Ukuran:  12
Tipe Data:  float64


In [27]:
# Jawaban 2.2
new_arr = np.sort(arr[:, 1:3], axis=None)
new_arr

array([ 2.,  3.,  6.,  7., 10., 11.])

In [21]:
# Jawaban 2.3
int_arr = arr.astype('i')
int_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)

In [22]:
# Jawaban 2.4
arr2_6 = arr.reshape(2, 6)
arr2_6

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]])

<h3> Berinteraksi dengan iris Dataset menggunakan numpy </h3>

In [24]:
from sklearn import datasets
iris = datasets.load_iris()

In [30]:
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

3.1 Bagaimana mengurutkan array pada **iris** kolom pertama?

3.2 Temukan *mean, median, modus, standar deviasi, percentile 25 dan 50* pada **iris** kolom kedua.

3.3 Temukan Arithmetic Mean, Geometric Mean, dan Weighted Mean pada **iris** kolom ketiga.

3.4 Temukan Correlation Coefficient pada **iris** kolom keempat

In [42]:
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [43]:
# Jawaban 3.1
iris_sort = iris.data[np.argsort(iris.data[:, 0])]
iris_sort

array([[4.3, 3. , 1.1, 0.1],
       [4.4, 3.2, 1.3, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.6, 1. , 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.6, 3.2, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 3. , 1.4, 0.3],
       [4.8, 3.4, 1.9, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7],
       [4.9, 3.1, 1.5, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3.6, 1.4, 0.1],
       [4.9, 3. , 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5. , 2. , 3.5, 1. ],
       [5. , 3.4, 1.5, 0.2],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3.6, 1.4, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.1, 2

In [48]:
# Jawaban 3.2
from scipy import stats as st
print("Mean kolom kedua: ", np.mean(iris.data[:, 1]))
print("Median kolom kedua: ", np.median(iris.data[:, 1]))
print("Modus kolom kedua: ", st.mode(iris.data[:, 1]).mode)
print("Standard Deviation kolom kedua: ", np.std(iris.data[:, 1]))
print("Percentile 25 kolom kedua: ", np.percentile(iris.data[:, 1], 25))
print("Percentile 50 kolom kedua: ", np.percentile(iris.data[:, 1], 50))

Mean kolom kedua:  3.0573333333333337
Median kolom kedua:  3.0
Modus kolom kedua:  [3.]
Standard Deviation kolom kedua:  0.4344109677354946
Percentile 25 kolom kedua:  2.8
Percentile 50 kolom kedua:  3.0


In [50]:
# Jawaban 3.3
import pandas as pd

In [54]:
print("Arithmetic Mean: ", iris.data[:, 2].mean())

print("Geometric Mean: ", st.gmean(iris.data[:, 2]))

weight = pd.Series(iris.data[:, 2])
count = weight.value_counts()
print("Weighted Mead: ", np.average(count.index, weights=count.values))

Arithmetic Mean:  3.7580000000000005
Geometric Mean:  3.238266844512273
Weighted Mead:  3.7580000000000005


In [58]:
# Jawaban 3.4
corr_coef, p_value = st.pearsonr(iris.data[:, 0], iris.data[:, 2])
print("Correlation Coefficient kolom pertama dan kolom keempat: %0.6f" %corr_coef)

Correlation Coefficient kolom pertama dan kolom keempat: 0.871754
